name: lyform_validators
description: Dart package to implement forms in an easy, fast and effective way using the bloc package
version: 0.13.0+1
homepage: https://github.com/lynotofficial/lynot-dart-flutter
repository: https://github.com/lynotofficial/lynot-dart-flutter/tree/master/packages/lyform_validators

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  lyform: ^0.13.0
  validators: ^3.0.0

dev_dependencies:
  lint: ">=1.10.0 <3.0.0"
  mocktail: ^0.3.0
  test: ^1.21.4
