name: lyform
description: Dart package to implement forms in an easy, fast and effective way using the bloc package
version: 0.13.0+1
homepage: https://github.com/lynotofficial/lynot-dart-flutter
repository: https://github.com/lynotofficial/lynot-dart-flutter/tree/master/packages/lyform

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  collection: ^1.16.0
  equatable: ^2.0.5

dev_dependencies:
  bloc_test: ^9.1.0
  lint: ">=1.10.0 <3.0.0"
  mocktail: ^0.3.0
  test: ^1.21.4
