name: lyform
description: Dart package to implement forms in an easy, fast and effective way using the bloc package
version: 0.14.0
homepage: https://github.com/lynotofficial/lynot-dart-flutter
repository: https://github.com/lynotofficial/lynot-dart-flutter/tree/master/packages/lyform

environment:
   sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.3
  collection: ^1.18.0
  equatable: ^2.0.5

dev_dependencies:
  bloc_test: ^9.1.5
  lint: ^2.3.0
  mocktail: ^1.0.2
  test: ^1.25.0
